In [1]:
import numpy as np

In [2]:
#создание нулевой матрицы размера mxn
def zeros(m, n):
    zeros_matrix = []
    for i in range(m):
        string = []
        for j in range(n):
            string.append(0)
        zeros_matrix.append(string) 
    return zeros_matrix   

In [3]:
A = [[1,2], [3,4], [5,6]]
B = [[7,8], [9,10], [11,12]]
c = 5

#### Сложение матриц

In [4]:
def addition(A, B):
    
    rows_A, cols_A = len(A), len(A[0])  
    rows_B, cols_B = len(B), len(B[0])
    
    if rows_A == rows_B and cols_A == cols_B:
        C = zeros(rows_A, cols_A)
        for i in range(rows_A):
            for j in range(cols_A):
                C[i][j] = A[i][j]+B[i][j]
    else:
        raise ValueError("Матрицы должны быть одной размерности")
    
    return C

In [5]:
addition(A,B)

[[8, 10], [12, 14], [16, 18]]

#### Вычитание матриц

In [6]:
def substruction(A, B):
    
    rows_A, cols_A = len(A), len(A[0])  
    rows_B, cols_B = len(B), len(B[0])
    
    if rows_A == rows_B and cols_A == cols_B:
        C = zeros(rows_A, cols_A)
        for i in range(rows_A):
            for j in range(cols_A):
                C[i][j] = A[i][j]-B[i][j]
    else:
        raise ValueError("Матрицы должны быть одной размерности")
    
    return C

In [7]:
substruction(B, A)

[[6, 6], [6, 6], [6, 6]]

#### Умножение матриц, умножение матрицы на число

In [8]:
A = [[1,2], [3,4]]
B = [[7,8], [9,10]]

In [9]:
def multiply(A, B):
            
    rows_A, cols_A = len(A), len(A[0])  

    if isinstance(A, list) and isinstance(B, list): 
        rows_B, cols_B = len(B), len(B[0])
        if cols_A==rows_B:
            C = zeros(rows_A, rows_B)
            for i in range(rows_A):
                for j in range(rows_B):
                    C[i][j] = sum([A[i][k]*B[k][j] for k in range(cols_A)])
        else:
            raise ValueError("Число столбцов матрицы А должно быть равно числу строк матрицы В")
    else:
        if (isinstance(A, list) and isinstance(B, int)):
            C = zeros(rows_A, cols_A)
            for i in range(rows_A):
                for j in range(cols_A):
                    C[i][j]=A[i][j]*B
        else:
            raise ValueError("Неправильный порядок аргументов")
       
    return C

In [10]:
multiply(A, B)

[[25, 28], [57, 64]]

In [11]:
np.dot(A, B)

array([[25, 28],
       [57, 64]])

In [12]:
multiply(A, c)

[[5, 10], [15, 20]]

In [13]:
np.dot(A, c)

array([[ 5, 10],
       [15, 20]])

#### Транспонирование

In [14]:
def transpose(matrix):
    rows = len(matrix)
    cols = len(matrix[0])
    matrix_T = zeros(cols, rows)
    for i in range(rows):
        for j in range(cols):
            matrix_T[j][i] = matrix[i][j]
    return matrix_T

In [15]:
transpose(A)

[[1, 3], [2, 4]]

In [16]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

#### Определитель

In [17]:
A = [[1, 2, 5, 6], [3, 4, 7, 8], [11, 16, 39, 9], [13, 19, 22, 9]]

In [18]:
import copy

In [19]:
def det(matrix):

    matrix_copy = copy.deepcopy(matrix)
    rows, cols  = len(matrix_copy),len(matrix_copy[0]) 
    det=1

    if cols==rows:
        for i in range(rows):
            if matrix_copy[i][i] == 0.0:
                raise ValueError("Деление на 0")
            for j in range(i+1, rows):
                coef = matrix_copy[j][i]/matrix_copy[i][i]
                for k in range(rows):
                     matrix_copy[j][k] = matrix_copy[j][k] - coef * matrix_copy[i][k]
        for i in range(rows):
            det = det*matrix_copy[i][i]
    else:
        raise ValueError("Матрица должна быть квадратная")
    
    return det

In [20]:
det(A)

1354.0

In [21]:
np.linalg.det(A)

1354.0000000000002

#### Деление матриц (задача о делении матриц сводится к умножению матрицы А на обратную матрицу матрице В)

In [22]:
A = [[1,2], [3,4]]
B = [[7,8], [9,10]]

In [23]:
#функция для получения обратной матрицы
def inv(matrix):
    if len(matrix) == len(matrix[0]):
        determinant = det(matrix)
        if determinant == 0:
            raise ValueError("Детерминант равен 0, обратной матрицы не существует")
        rows = len(matrix)
        minor_m =[]
        minor_m = minor_matrix(matrix)
        inv_m = transpose(minor_m)
        for i in range(len(inv_m)):
            for j in range(len(inv_m)):
                inv_m[i][j] = inv_m[i][j]/determinant
    else:
        raise ValueError("Матрица должна быть квадратная")
    return inv_m

In [24]:
#функция возвращает матрицу миноров
def minor_matrix(matrix):
    minors = zeros(len(matrix), len(matrix))
    for i in range(len(matrix)):
        for j in range(len(matrix)):
            matrix_copy = copy.deepcopy(matrix)
            matrix_copy.pop(i)
            for k in range(len(matrix[0]) - 1):
                matrix_copy[k].pop(j)
            minors[i][j] = ((-1)**(i+j))*det(matrix_copy)
    return minors

In [25]:
def division(A, B):
    return multiply(A, inv(B))

In [26]:
division(A, B)

[[3.9999999999999902, -2.999999999999992],
 [2.999999999999993, -1.9999999999999947]]

In [27]:
np.dot(A, np.linalg.inv(B))

array([[ 4., -3.],
       [ 3., -2.]])